# Generated by Django 5.0.4 on 2024-05-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
