# Generated by Django 5.0.4 on 2024-05-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_contact_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='roll_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
