# Generated by Django 5.0.4 on 2024-05-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_delete_contact_studentattendance_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
