# Generated by Django 5.0.6 on 2024-05-19 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentme_studentattendanceme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendanceme',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentme'),
        ),
    ]
